<a href="https://colab.research.google.com/github/koredlarajesh/PyTorch_practice/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import torch
from torch import nn
import numpy as np

In [14]:
data=[[1,2],[3,4]]

In [15]:
x_data=torch.tensor(data)

In [16]:
np_array=np.array(data)

In [18]:
x_np=torch.from_numpy(np_array)

In [19]:
x_ones=torch.ones_like(x_data)

In [22]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [20]:
x_rand=torch.rand_like(x_data,dtype=torch.float)

In [21]:
x_rand

tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])

In [23]:
shape=(2,3,)

In [24]:
rand_tensor=torch.rand(shape)

In [25]:
rand_tensor

tensor([[0.9408, 0.1332, 0.9346],
        [0.5936, 0.8694, 0.5677]])

In [26]:
ones_tensor=torch.ones(shape)

In [27]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [28]:
zeros_tensor=torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [29]:
tensor=torch.rand(2,3)

In [30]:
tensor.shape

torch.Size([2, 3])

In [31]:
tensor.dtype

torch.float32

In [32]:
tensor.device

device(type='cpu')

In [33]:
if torch.cuda.is_available():
  tensor=tensor.to("cuda")

In [34]:
tensor.device

device(type='cuda', index=0)

In [35]:
tensor=torch.ones(4,4)

In [36]:
tensor[0]

tensor([1., 1., 1., 1.])

In [37]:
tensor[1]

tensor([1., 1., 1., 1.])

In [38]:
tensor[2]

tensor([1., 1., 1., 1.])

In [39]:
tensor[:,0]

tensor([1., 1., 1., 1.])

In [40]:
tensor[:,-1]

tensor([1., 1., 1., 1.])

In [47]:
tensor=torch.randn([2,3])
tensor

tensor([[-0.0499,  0.5263, -0.0085],
        [ 0.7291,  0.1331,  0.8640]])

In [48]:
tensor[0]

tensor([-0.0499,  0.5263, -0.0085])

In [49]:
tensor[1]

tensor([0.7291, 0.1331, 0.8640])

In [50]:
tensor[:,0]

tensor([-0.0499,  0.7291])

In [51]:
tensor[:,-1]

tensor([-0.0085,  0.8640])

In [52]:
t1=torch.cat([tensor,tensor,tensor])

In [53]:
t1

tensor([[-0.0499,  0.5263, -0.0085],
        [ 0.7291,  0.1331,  0.8640],
        [-0.0499,  0.5263, -0.0085],
        [ 0.7291,  0.1331,  0.8640],
        [-0.0499,  0.5263, -0.0085],
        [ 0.7291,  0.1331,  0.8640]])

In [54]:
t2=torch.cat([tensor,tensor,tensor],dim=1)
t2

tensor([[-0.0499,  0.5263, -0.0085, -0.0499,  0.5263, -0.0085, -0.0499,  0.5263,
         -0.0085],
        [ 0.7291,  0.1331,  0.8640,  0.7291,  0.1331,  0.8640,  0.7291,  0.1331,
          0.8640]])

In [55]:
y1=tensor @ tensor.T
y2=tensor.matmul(tensor.T)
y3=torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)

tensor([[0.2796, 0.0264],
        [0.0264, 1.2957]])

In [56]:
tensor

tensor([[-0.0499,  0.5263, -0.0085],
        [ 0.7291,  0.1331,  0.8640]])

In [58]:
agg=tensor.sum()
agg

tensor(2.1941)

In [60]:
agg.item()

2.194114923477173

In [61]:
tensor

tensor([[-0.0499,  0.5263, -0.0085],
        [ 0.7291,  0.1331,  0.8640]])

In [63]:
tensor.add_(5)

tensor([[4.9501, 5.5263, 4.9915],
        [5.7291, 5.1331, 5.8640]])

In [64]:
t=torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [66]:
n=t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)